service: serverless-101

plugins:
  modules:
    - serverless-plugin-dynamodb
    - serverless-plugin-static-website

frameworkVersion: "^1.39.0"

provider:
  name: aws
  profile: awsug-serverless-101 #change with your profile
  runtime: nodejs8.10
  stage: test
  region: eu-west-1
  environment: 
    TABLE_TODO: ${self:custom.tables.todo.name}

custom:
  frontend: 
    bucket: ${self:service}-${self:provider.stage} #change this with a different name
    dir: './frontend'
    cacheControl: '0'
    deploy: sync
  tables:
    todo:
      name: ${self:service}-${self:provider.stage}-ToDo
      primaryKey: 
        name: id
        type: 'S'
      throughput:
        read: 1
        write: 1

functions:
  getTodo:
    handler: handler.get
    events:
      - http:
          path: /todo
          method: get
          integration: lambda
          cors: true
  putTodo:
    handler: handler.put
    events:
      - http:
          path: /todo
          method: put
          integration: lambda
          cors: true
  updateTodo:
    handler: handler.update
    events:
      - http:
          path: /todo/{id}
          method: post
          integration: lambda
          cors: true
  deleteTodo:
    handler: handler.delete
    events:
      - http:
          path: /todo/{id}
          method: delete
          integration: lambda
          cors: true
